#pragma once

#define CHESS_MAIN_WINDOW_SIZE_X			800
#define CHESS_MAIN_WINDOW_SIZE_Y			650

#define CHESS_BOARD_SIZE					600
#define CHESS_BOARD_DEFAULT_POS_X			10
#define CHESS_BOARD_DEFAULT_POS_Y			10
#define CHESS_BOARD_GRID_THICKNESS			2
#define CHESS_BOARD_FIELD_SIZE				((CHESS_BOARD_SIZE - 9 * CHESS_BOARD_GRID_THICKNESS) / 8)