#pragma once

#define CHESS_MAIN_WINDOW_SIZE_X			580
#define CHESS_MAIN_WINDOW_SIZE_Y			630

#define CHESS_BOARD_SIZE					(CHESS_BOARD_FIELD_SIZE * 8 + CHESS_BOARD_GRID_THICKNESS * 9)
#define CHESS_BOARD_DEFAULT_POS_X			10
#define CHESS_BOARD_DEFAULT_POS_Y			10
#define CHESS_BOARD_GRID_THICKNESS			6.45f
#define CHESS_BOARD_FIELD_SIZE				60